create table journal_data(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP default now() not null,
    day_rating integer not null ,
    deep_hours numeric not null ,
    journal_entry text not null,
    user_id integer references users(id) on delete cascade
);