create table observations(
    id integer primary key generated by default as identity,
    user_id uuid references users(id) on delete cascade not null,
    date_created timestamp default now() not null,
    observation text not null
);
