begin;

truncate
    users,
    journal_data,
    observations
    restart identity cascade;

Insert into users (username, password, email, first_name)
values
   ('mlambole0', '$2a$10$jSkStyzY9m6VJLOIWnSv3uLBbmmD4.Es/icrbxVjWzvXAM75Wpslq', 'mfish0@wsj.com', 'Menard'),
   ('tfalshaw1', '$2a$10$F2vF1NjsMuwJKNG1peyQru.yZG1TfNe7NieNT5tPzH8I5zFD9d9g2', 'tposkitt1@disqus.com', 'Timmie'),
   ('rplayfoot2', '$2a$10$3BG7gR.q3lNe2.zMbNLVaOD/Vd7qRWnaXCS9FwMIB26/WA9XgWgUO', 'rmcvicar2@oracle.com', 'Rhianon'),
   ('imechi3', '$2a$10$4.Gw4SdpwSjocKpgbF/QlexobMPI5VJGjdANzUv2.h8pnwffzG3SS', 'ihulme3@yolasite.com', 'Isis'),
   ('varlidge4', '$2a$10$BgpL9TcBp3/5WpsfAHEmRO/8Rv0kSxvB3hhZHqT3UtMpxgeSBZl1q', 'vhatchell4@nyu.edu', 'Vincent'),
   ('scocks5', '$2a$10$56lnc9E5h9WKZEnSiCsNUO5EbDuzzGNqj28Aj/T67MHK3VEYscDuW', 'sdumbelton5@rambler.ru', 'Smitty'),
   ('moscully6', '$2a$10$jwGwoasuyV1JABogEjVzyuRnZu3wLnbg0TxjWTbM6LtD.v/H1kWre', 'mpreator6@twitter.com', 'Mommy'),
   ('bgogerty7', '$2a$10$J5U85JdsbTOFsmB.H790LuWWBxXWpdEVn/D2DfDFyPF0.GtbsDhzS', 'bchittim7@symantec.com', 'Bertrand'),
   ('iescalero8', '$2a$10$HtoZ.YDDQFKkAZuFxl4Maehpxnz5SdU6sN5mawZM4HL1jP.LbqqAe', 'iarnhold8@seattletimes.com', 'Isidoro'),
   ('nskells9', '$2a$10$1pCNr4qjDJqHFiWeG3mkg.7XfxZjwmaIiH2vGoWqlihj3OP7OumCW', 'nstivens9@ed.gov', 'Ned');

Insert into journal_data (date_created, day_rating, deep_hours, journal_entry, user_id)
values
    ('2020-07-06', -2, 5, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 4),
    ('2020-03-14', 0, 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 8),
    ('2019-12-17', 2, 5, 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 5),
    ('2019-11-11', -1, 6, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 5),
    ('2020-03-28', 1, 7, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 10),
    ('2020-05-02', 1, 2, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 6),
    ('2020-07-17', -1, 1, 'Donec semper sapien a libero. Nam dui.', 6),
    ('2020-06-28', 2, 4, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 2),
    ('2020-05-04', 0, 3, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 6),
    ('2020-09-15', -1, 7, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1),
    ('2020-03-20', -2, 6, 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1),
    ('2020-07-22', 0, 5, 'Morbi non lectus.', 4),
    ('2020-06-13', 2, 4, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 6),
    ('2020-02-25', 2, 7, 'Pellentesque at nulla. Suspendisse potenti.', 2),
    ('2020-02-24', 2, 3, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4),
    ('2020-09-06', 1, 6, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 8),
    ('2020-06-21', 1, 7, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 5),
    ('2020-05-30', 1, 6, 'Donec dapibus. Duis at velit eu est congue elementum.', 10),
    ('2020-09-14', 0, 5, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 6),
    ('2020-01-25', -2, 8, 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1),
    ('2020-04-08', -2, 0, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 1),
    ('2020-03-07', -2, 0, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 3),
    ('2019-11-17', 1, 0, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 9),
    ('2020-05-18', -2, 4, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 8),
    ('2019-12-24', -1, 3, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 4),
    ('2020-08-11', -2, 2, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 5),
    ('2019-11-28', 1, 6, 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 8),
    ('2020-06-25', 0, 5, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 4),
    ('2020-05-01', 2, 4, 'Quisque porta volutpat erat.', 1),
    ('2020-05-18', 2, 3, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 1),
    ('2020-01-30', 0, 6, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 8),
    ('2020-04-01', 1, 7, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 7),
    ('2020-05-15', 0, 8, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 7),
    ('2019-12-13', 1, 2, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 4),
    ('2020-05-16', -2, 0, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 10),
    ('2020-07-18', 0, 7, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 6),
    ('2020-09-07', 2, 8, 'Nam dui.', 3),
    ('2020-06-12', -2, 5, 'Nunc nisl.', 5),
    ('2019-12-13', 1, 0, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 4),
    ('2020-11-03', 2, 0, 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 1),
    ('2020-08-23', 1, 8, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 5),
    ('2020-10-22', -1, 2, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 6),
    ('2020-03-19', 2, 0, 'Proin eu mi. Nulla ac enim.', 7),
    ('2020-10-08', 1, 1, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 7),
    ('2020-01-16', -2, 6, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 10),
    ('2020-03-30', 1, 6, 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 4),
    ('2020-06-21', 2, 6, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 9),
    ('2020-01-29', 1, 6, 'Proin risus. Praesent lectus.', 5),
    ('2019-12-29', 0, 8, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1),
    ('2020-08-11', 1, 6, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 2);

insert into observations( user_id, date_created, observation)
values
    (6, '2019-11-26', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.'),
    (2, '2020-03-04', 'Pellentesque ultrices mattis odio.'),
    (4, '2020-02-13', 'In hac habitasse platea dictumst.'),
    (4, '2020-01-07', 'Vivamus vel nulla eget eros elementum pellentesque.'),
    (3, '2020-10-08', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
    (7, '2020-03-08', 'Quisque porta volutpat erat.'),
    (7, '2020-06-22', 'Nullam porttitor lacus at turpis.'),
    (2, '2020-07-03', 'Duis ac nibh.'),
    (9, '2020-05-04', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.'),
    (2, '2020-01-18', 'Sed vel enim sit amet nunc viverra dapibus.'),
    (3, '2020-05-24', 'Vestibulum sed magna at nunc commodo placerat.'),
    (6, '2019-12-31', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.'),
    (10, '2020-02-25', 'Proin risus.'),
    (4, '2020-02-12', 'Nulla nisl.'),
    (7, '2020-04-12', 'Curabitur in libero ut massa volutpat convallis.'),
    (1, '2020-10-21', 'Aliquam erat volutpat.'),
    (3, '2020-05-06', 'Praesent blandit lacinia erat.'),
    (5, '2019-12-12', 'Praesent id massa id nisl venenatis lacinia.'),
    (4, '2020-03-05', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
    (6, '2020-07-02', 'Praesent lectus.'),
    (4, '2020-06-15', 'Aenean fermentum.'),
    (6, '2020-04-30', 'Nullam porttitor lacus at turpis.'),
    (3, '2020-05-04', 'Vivamus in felis eu sapien cursus vestibulum.'),
    (7, '2019-11-17', 'Nunc purus.'),
    (8, '2020-09-12', 'Proin at turpis a pede posuere nonummy.'),
    (2, '2020-02-10', 'Morbi porttitor lorem id ligula.'),
    (6, '2020-01-01', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'),
    (2, '2019-12-09', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.'),
    (3, '2019-11-24', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.'),
    (5, '2020-05-30', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.'),
    (5, '2020-06-12', 'Integer tincidunt ante vel ipsum.'),
    (2, '2020-05-17', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.'),
    (5, '2019-12-28', 'Nullam molestie nibh in lectus.'),
    (8, '2020-06-08', 'Integer non velit.'),
    (1, '2020-10-18', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.'),
    (8, '2020-02-03', 'Suspendisse ornare consequat lectus.'),
    (6, '2020-10-14', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.'),
    (7, '2020-10-16', 'Proin interdum mauris non ligula pellentesque ultrices.'),
    (4, '2020-08-29', 'Quisque porta volutpat erat.'),
    (6, '2020-10-30', 'Integer tincidunt ante vel ipsum.'),
    (8, '2020-02-10', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.'),
    (10, '2020-10-27', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
    (5, '2020-01-06', 'Integer ac leo.'),
    (10, '2020-05-21', 'Aenean fermentum.'),
    (8, '2019-11-14', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.'),
    (4, '2020-06-29', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.'),
    (8, '2020-01-14', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.'),
    (7, '2020-05-20', 'Ut tellus.'),
    (5, '2020-02-07', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.'),
    (4, '2020-01-11', 'Suspendisse potenti.');
Commit;